### ISSUE TITLE
get_model_designations() with source="zoltar" throwing an error

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#101] opened 2021-01-04 00:22 UTC
```
all_models <- get_all_models()
get_model_designations(all_models, source="zoltar")
```

gives this error
```
 Error: Internal error in `vec_proxy_assign_opts()`: `proxy` of type `character` incompatible with `value` proxy of type `NULL`.
Run `rlang::last_error()` to see where the error occurred. 
```

**Comment by Serena-Wang** [comment] 2021-01-04 06:04
@nickreich I pushed a fix to this issue. It is caused by a model called `CDDEP-ABM` which is outdated since summer. We do not have a model folder for it in the hub repo now, but it is still available in Zoltar. In Zoltar, the model designation is an empty string. I've changed `get_model_designations()` to return `NA` in this case and this is the only model that has this problem. Maybe we should delete this model in Zoltar?

**Comment by nickreich** [comment] 2021-01-04 15:28
I'd be more inclined to leave it in zoltar and just add a model designation. I think it would be ok to add this as primary.

**Comment by nickreich** [comment] 2021-01-04 15:32
https://github.com/reichlab/covid19-forecast-hub/blob/31640c790fb814b4a1e9af7e4d5ec2eb832dbb13/data-processed/CDDEP-SEIR_MCMC/metadata-CDDEP-SEIR_MCMC.txt

**Comment by nickreich** [comment] 2021-01-04 15:32
is this the same model? not quite the same name...

**Comment by Serena-Wang** [comment] 2021-01-04 16:24
Yeah not exactly the same. It seems that they only submitted one forecast file under CDDEP-ABM and switched to CDDEP-SEIR_MCMC later...

**Comment by Serena-Wang** [comment] 2021-01-06 07:40
@nick, Matt changed CDDEP-ABM's model designation to 'primary' on Zoltar data.

**Closed** 2021-01-06 07:42 UTC
